---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 16-04-2025

---
<h2>CDT Weekly Newsletter</h2><br><ul><li>Message from the Director</li><li>Lunch and Learn Seminar</li><li>Student reps for next academic year</li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b>Message from the Director</b><br><p class="x_MsoNormal" style="margin-bottom: 9.6pt; line-height: 106%;"><span lang="EN-US" data-olk-copy-source="MessageBody">Thanks everyone for your engagement and input to what was a great Spring conference in a great venue. I really enjoyed it and so did the participating members of our advisory board. Special thanks to Andrew and Harry as student organisers, and Ole and Suzanne for making everything run so smoothly. Please don&rsquo;t hesitate to post about it on your social networks. </span></p><br><br><b>Lunch and Learn Seminar</b><br><p class="x_MsoNormal" style="margin-bottom: 9.6pt; line-height: 106%;"><span lang="EN-US" data-olk-copy-source="MessageBody">There will be no Lunch and Learn Seminar this week. The next meeting will be on Wednesday <strong>30<sup> </sup>April</strong>.</span></p><br><br><b>Student reps for next academic year</b><br><p class="x_MsoNormal" style="margin-bottom: 9.6pt; line-height: 106%;"><span data-olk-copy-source="MessageBody">It&rsquo;s time to organise student reps for the next academic year, with two reps being needed for each cohort. Roles still to be filled for CDT23 and CDT22. Please email </span><span lang="EN-US" style="font-size: 11.0pt; line-height: 106%; font-family: 'Calibri',sans-serif;"><a title="mailto:iai-cdt@bristol.ac.uk" href="mailto:iai-cdt@bristol.ac.uk" data-linkindex="1"><span lang="EN-GB" style="font-size: 12pt; line-height: 106%; font-family: 'Aptos', sans-serif; color: rgb(5, 99, 193) !important;">iai-cdt@bristol.ac.uk</span></a></span> by <strong>17 April</strong> if you are willing to take on the role.</p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b>Bristol Doctoral College (BDC) Events Calendar - 2025-04-18</b><br>